# Generated by Django 3.2.8 on 2021-10-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idclasse', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Modificado',
            fields=[
                ('com_acessorios', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome_veiculo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('sem_acessorios', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome_veiculo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=45)),
                ('ano_fabricacao', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
                ('ano_modelo', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.classe')),
            ],
        ),
    ]
