# Generated by Django 3.2.5 on 2021-10-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('codigo_acessorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_acessorio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rg', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=45)),
                ('nome_completo', models.CharField(max_length=65)),
                ('cep', models.CharField(max_length=15)),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=45)),
                ('ano_fabricacao', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
                ('ano_modelo', models.IntegerField()),
                ('acessorios', models.ManyToManyField(to='bd.Acessorio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.cliente')),
            ],
        ),
    ]
